;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((c++-mode
  ;; (company-clang-arguments . ("-I/ag/z3/spacer/src"
  ;;                             "-I/ag/z3/spacer/src/ackermannization"
  ;;                             "-I/ag/z3/spacer/src/api"
  ;;                             "-I/ag/z3/spacer/src/api/c++"
  ;;                             "-I/ag/z3/spacer/src/api/dll"
  ;;                             "-I/ag/z3/spacer/src/api/java"
  ;;                             "-I/ag/z3/spacer/src/api/ml"
  ;;                             "-I/ag/z3/spacer/src/api/python"
  ;;                             "-I/ag/z3/spacer/src/ast"
  ;;                             "-I/ag/z3/spacer/src/ast/fpa"
  ;;                             "-I/ag/z3/spacer/src/ast/macros"
  ;;                             "-I/ag/z3/spacer/src/ast/normal_forms"
  ;;                             "-I/ag/z3/spacer/src/ast/pattern"
  ;;                             "-I/ag/z3/spacer/src/ast/proof_checker"
  ;;                             "-I/ag/z3/spacer/src/ast/rewriter"
  ;;                             "-I/ag/z3/spacer/src/ast/rewriter/bit_blaster"
  ;;                             "-I/ag/z3/spacer/src/ast/simplifier"
  ;;                             "-I/ag/z3/spacer/src/ast/substitution"
  ;;                             "-I/ag/z3/spacer/src/cmd_context"
  ;;                             "-I/ag/z3/spacer/src/cmd_context/extra_cmds"
  ;;                             "-I/ag/z3/spacer/src/duality"
  ;;                             "-I/ag/z3/spacer/src/interp"
  ;;                             "-I/ag/z3/spacer/src/interp/foci2stub"
  ;;                             "-I/ag/z3/spacer/src/math"
  ;;                             "-I/ag/z3/spacer/src/math/automata"
  ;;                             "-I/ag/z3/spacer/src/math/euclid"
  ;;                             "-I/ag/z3/spacer/src/math/grobner"
  ;;                             "-I/ag/z3/spacer/src/math/hilbert"
  ;;                             "-I/ag/z3/spacer/src/math/interval"
  ;;                             "-I/ag/z3/spacer/src/math/polynomial"
  ;;                             "-I/ag/z3/spacer/src/math/realclosure"
  ;;                             "-I/ag/z3/spacer/src/math/simplex"
  ;;                             "-I/ag/z3/spacer/src/math/subpaving"
  ;;                             "-I/ag/z3/spacer/src/math/subpaving/tactic"
  ;;                             "-I/ag/z3/spacer/src/model"
  ;;                             "-I/ag/z3/spacer/src/muz"
  ;;                             "-I/ag/z3/spacer/src/muz/base"
  ;;                             "-I/ag/z3/spacer/src/muz/bmc"
  ;;                             "-I/ag/z3/spacer/src/muz/clp"
  ;;                             "-I/ag/z3/spacer/src/muz/dataflow"
  ;;                             "-I/ag/z3/spacer/src/muz/ddnf"
  ;;                             "-I/ag/z3/spacer/src/muz/duality"
  ;;                             "-I/ag/z3/spacer/src/muz/fp"
  ;;                             "-I/ag/z3/spacer/src/muz/pdr"
  ;;                             "-I/ag/z3/spacer/src/muz/rel"
  ;;                             "-I/ag/z3/spacer/src/muz/spacer"
  ;;                             "-I/ag/z3/spacer/src/muz/tab"
  ;;                             "-I/ag/z3/spacer/src/muz/transforms"
  ;;                             "-I/ag/z3/spacer/src/nlsat"
  ;;                             "-I/ag/z3/spacer/src/nlsat/tactic"
  ;;                             "-I/ag/z3/spacer/src/opt"
  ;;                             "-I/ag/z3/spacer/src/parsers"
  ;;                             "-I/ag/z3/spacer/src/parsers/smt"
  ;;                             "-I/ag/z3/spacer/src/parsers/smt2"
  ;;                             "-I/ag/z3/spacer/src/parsers/util"
  ;;                             "-I/ag/z3/spacer/src/qe"
  ;;                             "-I/ag/z3/spacer/src/sat"
  ;;                             "-I/ag/z3/spacer/src/sat/sat_solver"
  ;;                             "-I/ag/z3/spacer/src/sat/tactic"
  ;;                             "-I/ag/z3/spacer/src/shell"
  ;;                             "-I/ag/z3/spacer/src/smt"
  ;;                             "-I/ag/z3/spacer/src/smt/params"
  ;;                             "-I/ag/z3/spacer/src/smt/proto_model"
  ;;                             "-I/ag/z3/spacer/src/smt/tactic"
  ;;                             "-I/ag/z3/spacer/src/solver"
  ;;                             "-I/ag/z3/spacer/src/tactic"
  ;;                             "-I/ag/z3/spacer/src/tactic/aig"
  ;;                             "-I/ag/z3/spacer/src/tactic/arith"
  ;;                             "-I/ag/z3/spacer/src/tactic/bv"
  ;;                             "-I/ag/z3/spacer/src/tactic/core"
  ;;                             "-I/ag/z3/spacer/src/tactic/fpa"
  ;;                             "-I/ag/z3/spacer/src/tactic/nlsat_smt"
  ;;                             "-I/ag/z3/spacer/src/tactic/portfolio"
  ;;                             "-I/ag/z3/spacer/src/tactic/sls"
  ;;                             "-I/ag/z3/spacer/src/tactic/smtlogics"
  ;;                             "-I/ag/z3/spacer/src/tactic/ufbv"
  ;;                             "-I/ag/z3/spacer/src/util"
  ;;                             "-I/opt/local/include"
  ;;                             "-D_NO_OMP_"
  ;;                             ))
  
  (c-basic-offset . 4))
 (c-mode
  (c-basic-offset . 4)))



 

